services:
  backend:
    build: 
      dockerfile: ./compose/backend/Dockerfile
      context: .
    ports:
      - "5000:5000"
    env_file: .env
    environment:
      OMDB_API_KEY: ${OMDB_API_KEY}
      OMDB_URL: ${OMDB_URL}
    volumes:
      - ./backend:/app
    command: "npm run dev"

  frontend:
    build: 
      dockerfile: ./compose/frontend/Dockerfile
      context: .
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
    volumes:
      - ./frontend:/app
    command: "npm start"


